apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywp
  name: mywp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywp
  type: NodePort
status:
  loadBalancer: {}
