apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywp
  name: mywp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywp
    spec:
      containers:
      - image: docker.io/wordpress:latest
        name: wordpress
        env: 
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_NAME
          value: unnati
        - name: WORDPRESS_DB_PASSWORD
          value: redhat 
